M_17/mysite/apiapp/urls.py
from django.urls import path

from .views import (
    hello_world_view,
    GroupsListView,
                    )

app_name = "apiapp"

urlpatterns = [
    path("hello/", hello_world_view, name="hello"),
    path("groups/", GroupsListView.as_view(), name="groups"),
]

M_17/mysite/myauth/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path
from .views import (
    get_cookie_view,
    set_cookie_view,
    set_session_view,
    get_session_view,
    # logout_view,
    MyLogoutView,
    AboutMeView,
    RegisterView,
    FooBarView,
    ProfileUpdateView,
    UserProfileListView,
    ProfileView,
    HelloView,
)


app_name = "myauth"

urlpatterns = [
    # path("login/", login_view, name="login"),
    path(
        "login/",
        LoginView.as_view(
            template_name="myauth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login"),
    path("hello/", HelloView.as_view(), name="hello"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    # path("logout/", logout_view, name="logout"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="update_profile"),
    path("profile/<int:pk>/", ProfileView.as_view(), name="profile"),
    path("users/", UserProfileListView.as_view(), name="user_list"),
    path("register/", RegisterView.as_view(), name="register"),
    path("cookie/get/", get_cookie_view, name="cookie-get"),
    path("cookie/set/", set_cookie_view, name="cookie-set"),
    path("session/get/", get_session_view, name="session-get"),
    path("session/set/", set_session_view, name="session-set"),

    path("foo-bar/", FooBarView.as_view(), name="foo-ba"),
]

M_17/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
import debug_toolbar
from BlogApp.sitemap import BlogSitemap
from shopapp.sitemap import ProductSitemap, OrderSitemap


sitemaps = {
    'Articles': BlogSitemap,
    'Orders': OrderSitemap,
    'Products': ProductSitemap,
}


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('apiapp.urls')),
    path('blog/', include('BlogApp.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

urlpatterns += i18n_patterns(
    path('shop/', include('shopapp.urls')),
    path('accounts/', include('myauth.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

M_17/mysite/shopapp/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (ShopIndexView,
                    GroupsListView,
                    ProductDetailsView,
                    ProductsListView,
                    OrderCreateView,
                    OrdersListView,
                    OrderDetailView,
                    ProductCreateView,
                    ProductUpdateView,
                    OrderUpdateView,
                    ProductDeleteView,
                    OrderDeleteView,
                    ProductsDataExportView,
                    OrdersDataExportView,
                    ProductViewSet,
                    OrderViewSet,
                    )

app_name = "shopapp"

routers = DefaultRouter()
routers.register("products", ProductViewSet)
routers.register("orders", OrderViewSet)

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("api/", include(routers.urls)),
    path("groups/", GroupsListView.as_view(), name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="create_product"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="update_product"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="delete_product"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/create/", OrderCreateView.as_view(), name="create_order"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="update_order"),
    path("orders/<int:pk>/archive/", OrderDeleteView.as_view(), name="delete_order"),
    path("products/export/", ProductsDataExportView.as_view(), name="products_export"),
    path("orders/export/", OrdersDataExportView.as_view(), name="orders_export"),
]

M_17/mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )


class Product(models.Model):
    """
    Модель Product представляет товар,
    который можно продавать в интернет-магазине.

    Заказы тут: :model:`shopapp.order`
    """

    class Meta:
        ordering = ["name", "price"]
        verbose_name = _("Product")
        verbose_name_plural = _("Products")

    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    products_count = models.IntegerField(default=1)
    is_instock = models.BooleanField(default=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, default=1)
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)

    # @property
    # def description_short(self):
    #     if len(self.description) < 50:
    #         return self.description
    #     return self.description[:48] + "..."
    def get_absolute_url(self):
        return reverse('shopapp:product_details', args=[self.pk])

    def __str__(self):
        return f"Product id {self.pk}, name {self.name!r})"


def product_images_directory_path(instance: "ProductImage", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)


class Order(models.Model):
    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    delivery_address = models.TextField(null=False, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")
    archived = models.BooleanField(default=False)
    receipt = models.FileField(null=True, upload_to='orders/receipts/')

    def get_absolute_url(self):
        return reverse('shopapp:order_details', args=[self.pk])

    def __str__(self):
        return f"Order id = {self.pk}"

M_17/mysite/shopapp/views.py
"""
В этом модуле лежат различные наборы представлений.

Разные view для интернет-магазина: товары, заказы и т.д.
"""
from timeit import default_timer

from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import ProductForm, OrderForm, GroupForm
from .models import Product, Order, ProductImage
from .serializers import ProductSerializer, OrderSerializer
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend
from drf_spectacular.utils import extend_schema, OpenApiResponse
import logging


logger = logging.getLogger(__name__)


# API
@extend_schema(description="Product views CRUD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений для действий над Product.

    Полный CRUD для действий над товаром.
    """

    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["name", "description"]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_filters = [
        "name",
        "price",
        "discount",
        "archived",
    ]

    @extend_schema(summary="Get one product by ID",
                   description="Retrieves **product**, returns 404 if not found.",
                   responses={
                       200: ProductSerializer,
                       404: OpenApiResponse(description="Empty response, product by ID not found."),
                   })
    def retrieve(self, *args, **kwargs):
        return super().retrieve(*args, **kwargs)


# API
class OrderViewSet(ModelViewSet):
    """
    Набор представлений для действий над Order.

    Полный CRUD для действий над заказом.
    """

    queryset = Order.objects.all()
    serializer_class = OrderSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = ["delivery_address", "promocode"]
    filterset_fields = [
                        "products",
                        "delivery_address",
                        "promocode",
                        "user",
                        "created_at",
                        ]
    ordering_filters = [
        "user",
        "created_at",
        "archived",
    ]


class ShopIndexView(View):
    """ Главная страница. """

    def get(self, request: HttpRequest) -> HttpResponse:
        first_header = "Hello! This is a Shop Index page!"
        context = {
            "time_running": default_timer(),
            "first_header": first_header,
            "items": 1,
        }
        logger.info('Загружена главная страница')
        return render(request, "shopapp/shop-index.html", context=context)


class GroupsListView(View):
    """ Представление для списка групп пользователей и создания группы. """

    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm,
            "groups": Group.objects.prefetch_related('permissions').all(),
        }
        return render(request, "shopapp/groups-list.html", context=context)

    def post(self, request: HttpRequest):
        """ Создание группы. """
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(request.path)


class ProductDetailsView(DetailView):
    """ Представление для информации по товару. """

    template_name = "shopapp/product-details.html"
    # model = Product
    queryset = Product.objects.prefetch_related("images")
    # context = {
    #     "images": images,
    # }
    context_object_name = "product"
    # def get(self, request: HttpRequest, pk:int) -> HttpResponse:
    #     product = get_object_or_404(Product, pk=pk)
    #     context = {
    #         "product": product,
    #     }
    #     return render(request, "shopapp/product-details.html", context=context)


class ProductsListView(ListView):
    template_name = "shopapp/products-list.html"
    # model = Product
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


class ProductCreateView(UserPassesTestMixin, CreateView):
    def test_func(self):
        # return self.user.groups.filter(name="secret_group").exists()
        return self.request.user.is_staff

    def form_valid(self, form):
        # success_url = self.get_success_url()
        form.instance.created_by = self.request.user
        logger.info("Загружена страница создания товара")
        return super().form_valid(form)

    model = Product
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products_list")


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    def test_func(self):
        object = self.get_object()
        req_perms = [
            "shopapp.change_product",
        ]
        return self.request.user.is_superuser or self.request.user == object.created_by and\
               self.request.user.has_perms(req_perms)

    model = Product
    fields = "name", "price", "description", "discount", "preview"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        logger.info("Product updated successfully.")
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class OrdersListView(LoginRequiredMixin, ListView):
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
        .only("pk", "user", "user__username",
              "user__first_name", "delivery_address",
              "promocode", "created_at")
        .filter(archived=False)
        .order_by("pk")
    )
    paginate_by = 20


class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = (
        Order.objects.select_related("user").prefetch_related("products")
    )


class OrderCreateView(CreateView):
    model = Order
    fields = "user", "delivery_address", "promocode", "products"
    success_url = reverse_lazy("shopapp:orders_list")


class OrderUpdateView(UpdateView):
    model = Order
    fields = "user", "delivery_address", "promocode", "products"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        logger.info("Order updated successfully.")
        return reverse(
            "shopapp:order_details",
            kwargs={"pk": self.object.pk},
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:orders_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class ProductsDataExportView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        products = Product.objects.order_by("pk").all()
        products_data = [
            {
                "pk": product.pk,
                "name": product.name,
                "price": product.price,
                "archived": product.archived,
            }
            for product in products
        ]
        logger.info("JSON with products was exported successfully.")
        return JsonResponse({"products": products_data})


class OrdersDataExportView(UserPassesTestMixin, View):
    def test_func(self):
        return self.request.user.is_staff

    def get(self, request: HttpRequest) -> HttpResponse:
        orders = Order.objects.filter(archived=False)
        orders_data = []
        for order in orders:
            product_ids = order.products.values_list("pk", flat=True)
            order_info = {
                "pk": order.pk,
                "delivery_address": order.delivery_address,
                "promocode": order.promocode,
                "user": order.user.pk,
                "products": list(product_ids),
            }
            orders_data.append(order_info)
        logger.info("Orders' data was exported successfully.")
        return JsonResponse({"orders": orders_data})

M_17/mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base title
        {% endblock %}
    </title>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}
</style>
</head>
<body>
{% block body %}
    Base body
{% endblock %}
<br>
<div>
    It is {% now "h:i" %} now
</div>
<div>
    {% now 'l' as current_weekday %}
    Today is {{ current_weekday }}
</div>
</body>
</html>

M_17/mysite/shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Create product
{% endblock %}

{% block body %}
    <h1>
    Create a new product
    </h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>

        <span>OLD</span>
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            > Back to products list
        </a>
    </div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups list
{% endblock %}

{% block body %}
    <h1>Groups:</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
    {% if not groups %}
        <h2>No groups yet</h2>
    {% else %}
        <ul>
        {% for group in groups %}
            <li>
                <div>{{ group.name }}</div>
                <ul>
                    {% for permission in group.permissions.all %}
                        <li>
                            {{ permission.name }}
                            (<code>{{ permission.codename }}</code>)
                        </li>
                    {% endfor %}

                </ul>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends "shopapp/base.html" %}

{% block title %}
Confirm delete {{ object.name }}
{% endblock %}

{% block body %}
    <h1>
    Are you sure you want to archive {{ object.name }}?
    </h1>
    <br>
<div>
    <a href="{% url 'shopapp:order_details' pk=object.pk %}">
    > Back to an order</a>
</div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Archive</button>
        </form>
    </div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/order_detail.html
{% extends "shopapp/base.html" %}

{% block title %}
Order # {{ object.pk }}
{% endblock %}

{% block body %}
<h1>Order #{{ object.pk }} details:</h1>
    <div>
    <p>Ordered by: {% firstof object.user.first_name object.user.username %}</p>
    <p>Promocode: <code>{{ object.promocode }}</code></p>
    <p>Delivery address: {{ object.delivery_address }}</p>
    </div>
    <div>
    Product in an order:
    <ul>{% for product in object.products.all %}
    <li>{{ product.name }} for {{ product.price }}</li> {%  endfor %}</ul>
    </div>
    <div><div>Archived: {{ object.archived }}</div></div>
    <div>
        <a href="{% url 'shopapp:update_order' pk=order.pk %}">
            Update order
        </a>
    </div>
    <div>
        <a href="{% url 'shopapp:delete_order' pk=order.pk %}">
            Delete order
        </a>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            Orders list
        </a>
    </div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/order_form.html
{% extends "shopapp/base.html" %}

{% block title %}
Create order
{% endblock %}

{% block body %}
<h1>Create an order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:orders_list' %}">
            Orders list
        </a>
    </div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders List
{% endblock %}

{% block body %}
    <h2>Orders:</h2>
    <div>
    {% if object_list %}

        <div>                <table>
                    <tr>
                        <th>Details:</th><th>Username:</th>   <th>Delivery address</th>  <th>Promocode</th> <th>Order created at</th> <th>Products</th>
                    </tr>
        {% for order in object_list %}


                <tr>
                    <td><a href="{% url 'shopapp:order_details' pk=order.pk %}">Order #{{ order.pk }}</a></td>
                    <td>{% firstof order.user.first_name order.user.username %}</td>  <td>{{ order.delivery_address }}</td>
                    <td>{{ order.promocode }}</td>   <td>{{ order.created_at }}</td>
                    <td>
                        {% for product in order.products.all %}
                            <span>{{ product.name }} for {{ product.price }} &#8381;<br></span>
                        {% endfor %}

                    </td>
                </tr>


        {% endfor %}
                            </table>
    {% else %}
        <h2>No orders yet.</h2></div>
    {% endif %}
    </div>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    <div>
        <a href="{% url 'shopapp:create_order' %}">
            Create an order
        </a>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Products list
        </a>
    </div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/order_update_form.html
{% extends "shopapp/base.html" %}

{% block title %}
Update order
{% endblock %}

{% block body %}
<h1>Update an order</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:order_details' pk=object.pk %}">
            Back to order #{{ object.pk }}
        </a>
    </div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/orders-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if orders %}
    <div>
      {% for order in orders %}
        <div>
          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>
            Product in order:
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}

            </ul>
          </div>

        </div>
      {% endfor %}

    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/product-details.html
{% extends "shopapp/base.html" %}
{% load i18n %}

{% block title %}
{% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}
        <h1>{% translate 'Product details' %}:</h1>
        <div><h2><strong>{{ product.name }}</strong></h2>
        <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
        <div>{% translate 'Price' %}: {{ product.price }}</div>
        <div>{% translate 'Discount' %}: {{ product.discount }}%</div>
        <div>{% translate 'Archived' %}: {{ product.archived }}</div>
        <div>{% translate 'In stock' %}: {{ product.is_instock }}</div>
    {% if product.preview %}
        <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}" width="200">
    {% endif %}
<h2>
{% blocktranslate count product.images.count as image_count %}
    There is only {{ image_count }} image:
    {% plural %}
    There are {{ image_count }} images:
 {% endblocktranslate %}
</h2>
<div>
    {% translate 'No images uploaded yet.' as no_img %}
    {% for img in product.images.all %}
    <div>
        <img src="{{ img.image.url }}" alt="{{ img.image.name }}" width="450">
    <div>{{ img.description }}</div>
    </div>
    {% empty %}
        <div>{{ no_img }}</div>
    {% endfor %}

</div>
</div>
    {% if perms.shopapp.change_product %}
        {% url 'shopapp:delete_product' pk=product.pk as archive_prod %}
        {% url 'shopapp:products_list' as prod_list %}

    <div><a href="{% url 'shopapp:update_product' pk=product.pk %}">
        {% translate 'Update product' %}
    </a></div>
    {% endif %}
    {% blocktranslate %}
    <div><a href="{{ archive_prod }}">
        Archive product
    </a></div>
    <div><a href="{{ prod_list }}">
        > Back to products list
    </a>
    {% endblocktranslate %}</div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/product_form.html
{% extends "shopapp/base.html" %}

{% block title %}
Create product
{% endblock %}

{% block body %}
<h1>Create product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:products_list' %}">
            Products list
        </a>
    </div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/product_update_form.html
{% extends "shopapp/base.html" %}

{% block title %}
Update product
{% endblock %}

{% block body %}
<h1>Update product</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
    </div>
    <div>
        <a href="{% url 'shopapp:product_details' pk=object.pk %}">
            Back to product #{{ object.pk }}
        </a>
    </div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Products list' %}
{% endblock %}

{% block body %}
  <h1>{% translate 'Products' %}:</h1>
  {% if products %}
      <div>
      {% blocktranslate count product_count=products|length %}
          There is only one product.
          {% plural %}
          There are {{ product_count }} products.
      {% endblocktranslate %}
      </div>
        <div>
        {% for product in products %}
            <div>
            <p>{% translate 'Name' context 'product name' %}:
                <a href="{% url 'shopapp:product_details' pk=product.pk %}">{{ product.name }}</a></p>
            <p>{% translate 'Price' %}: {{ product.price }}</p>
            {% translate 'no discount' as no_discount %}
            <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>
            <p>{% translate 'In Stock' %}: {% if product.is_instock %}
                <span>{% translate 'Yes' %}</span>
                {% else %}
                <span>{% translate 'No' %}</span>
            {% endif %} </p>
            {% if product.preview %}
                <img src="{{ product.preview.url }}" alt="{{ product.preview.name }}" width="100">
            {% endif %}
            </div><br>
        {% endfor %}

        </div>
  {% else %}
        {% blocktranslate %}
            <h3>No products yet</h3>
        {% endblocktranslate %}
  {% endif %}

  {% if perms.shopapp.add_product %}
    <div>
        <a href="{% url 'shopapp:create_product' %}">
            {% translate 'Create a product' %}
        </a>
    </div>
  {% endif %}
  <div>
    <a href="{% url 'shopapp:orders_list' %}">
        {% translate 'Orders list' %}
    </a>
  </div>
{% endblock %}

M_17/mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
Shop Index
{% endblock %}

{% block body %}

<h1>{{ first_header|center:"100" }}</h1>
<div>
    Time running: {{ time_running }}
</div>
<div>
    {% lorem 5 p random %}
</div>
<div>
    {% now "h:i" as cur_time %}
    Now {{ cur_time|date:"e" }} test1
</div>
    <div>
    <strong>
        You have {{ items }} cherr{{ items|pluralize:"y,ies" }}
    </strong>
    </div>
    <div>
    My profile - <a href="{% url 'myauth:about-me' %}">{{ user.pk  }}</a>
    </div>
{% endblock %}