M_17/mysite/BlogApp/urls.py
from django.urls import path, include
from .views import (
    ArticlesListView,
    get_articles_in_custom_format,
    ArticlesDetailView,
)

from .feeds import LatestArticlesFeed

app_name = "BlogApp"

urlpatterns = [
    path("", get_articles_in_custom_format, name="articles"),
    path("articles/", ArticlesListView.as_view(), name="articles"),
    path("articles/<int:pk>/", ArticlesDetailView.as_view(), name="article"),
    path('latest/feed/', LatestArticlesFeed(), name="rss"),
]

M_17/mysite/apiapp/urls.py
from django.urls import path

from .views import (
    hello_world_view,
    GroupsListView,
                    )

app_name = "apiapp"

urlpatterns = [
    path("hello/", hello_world_view, name="hello"),
    path("groups/", GroupsListView.as_view(), name="groups"),
]

M_17/mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
import debug_toolbar
from BlogApp.sitemap import BlogSitemap
from shopapp.sitemap import ProductSitemap, OrderSitemap


sitemaps = {
    'Articles': BlogSitemap,
    'Orders': OrderSitemap,
    'Products': ProductSitemap,
}


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api/', include('apiapp.urls')),
    path('blog/', include('BlogApp.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),

]

urlpatterns += i18n_patterns(
    path('shop/', include('shopapp.urls')),
    path('accounts/', include('myauth.urls')),
)

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

M_17/mysite/BlogApp/models.py
from django.db import models
from django.urls import reverse


class Author(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    bio = models.TextField(blank=True)


class Category(models.Model):
    name = models.CharField(max_length=40)


class Tag(models.Model):
    name = models.CharField(max_length=20)


class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(blank=False)
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def get_absolute_url(self):
        return reverse('BlogApp:article', args=[self.pk])

    def __str__(self) -> str:
        return f"{self.title[:30]}"

M_17/mysite/BlogApp/views.py
from django.core import serializers
from django.http import HttpResponse, HttpResponseBadRequest, HttpRequest
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from BlogApp.models import Article
import logging


logger = logging.getLogger(__name__)


class ArticlesListView(ListView):
    template_name = "BlogApp/articles_list.html"
    context_object_name = "articles"
    queryset = (Article.objects
                .select_related('author', 'category')
                .prefetch_related('tags')
                .defer('content')
                .order_by("pk"))


def get_articles_in_custom_format(request: HttpRequest) -> HttpResponse:
    format = request.GET['format']
    if format not in ['xml', 'json', 'yaml']:
        return HttpResponseBadRequest()
    data = serializers.serialize(format, Article.objects.all())
    return HttpResponse(data)


class ArticlesDetailView(DetailView):
    model = Article
    template_name = 'BlogApp/article_detail.html'

M_17/mysite/BlogApp/templates/blogapp/article.html
{% extends "BlogApp/base.html" %}

{% block title %}
Article {{ object.pub_date }}
{% endblock %}

{% block body %}
<h1>{{ object.title }}:</h1>
    <div>
    <p>{{ object.category.name }}</p>
    <p>{{ object.content }}</p>
    </div>
    <div>
    <p>Publication date: {{ object.pub_date }}</p>
    Product in an order:
    <ul>{% for tag in object.tags.all %}
    <li>{{ tag.name }}</li> {%  endfor %}</ul>
    </div>
        <div>
        <a href="{% url 'BlogApp:articles' %}">
            Back to the Articles
        </a>
    </div>
{% endblock %}

M_17/mysite/BlogApp/templates/blogapp/article_detail.html
{% extends "BlogApp/base.html" %}

{% block title %}
Article {{ object.pub_date }}
{% endblock %}

{% block body %}
<h1>{{ object.title }}:</h1>
    <div>
    <p>{{ object.category.name }}</p>
    <p>{{ object.content }}</p>
    </div>
    <div>
    <p>Publication date: {{ object.pub_date }}</p>
    Product in an order:
    <ul>{% for tag in object.tags.all %}
    <li>{{ tag.name }}</li> {%  endfor %}</ul>
    </div>
        <div>
        <a href="{% url 'BlogApp:articles' %}">
            Back to the Articles
        </a>
    </div>
{% endblock %}

M_17/mysite/BlogApp/templates/blogapp/articles_list.html
{% extends 'BlogApp/base.html' %}

{% block title %}
    Articles
{% endblock %}

{% block body %}
    <h2>Articles:</h2>
    <div>
    {% if object_list %}
        <div>
            <table>
                <tr>
                    <th>Title:</th><th>Pub. Date:</th>   <th>Author:</th>  <th>Category</th> <th>Tags</th>
                </tr>
        {% for article in object_list %}
            <tr>
                <td><a href="{% url 'BlogApp:article' pk=article.pk %}">{{ article.title }}</a></td>
                <td>{{ article.pub_date }}</td>
                <td>{{ article.author.name }}
                <td>{{ article.category.name }}</td>
                <td>
                    {% for tag in article.tags.all %}
                        <span>{{ tag.name }} &nbsp;&nbsp;</span>
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
            </table>
    {% else %}
        <h2>No articles yet.</h2>
        </div>
    {% endif %}
    </div>
    <a href="{% url 'BlogApp:rss' %}">RSS Feed</a>
{#    <div>#}
{#        <a href="{% url 'BlogApp:create_article' %}">#}
{#            Create new article#}
{#        </a>#}
{#    </div>#}
{% endblock %}

M_17/mysite/BlogApp/templates/blogapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base title
        {% endblock %}
    </title>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}
</style>
</head>
<body>
{% block body %}
    Base body
{% endblock %}
<br>
</body>
</html>